### ISSUE TITLE
Set up umami analytics

### ISSUE THREAD

**Issue by stamatim** [stamatim/personal-site#8]
#### Phase 1: [Setup](https://umami.is/docs/running-on-digitalocean)

- [ ] Install Ubuntu
- [ ] Install Database (MySQL)
- [ ] Install Node.js
- [ ] Install Umami
- [ ] Run Umami
- [ ] Proxy with NGINX
- [ ] Add an SSL Certificate

#### Phase 4: [Collect Data](https://umami.is/docs/collect-data)
